apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8nsu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-8nsu@sha256:890f8eee1cedc68ff4ba401c16d95d894ceaa94a49bc7ad4fe40f2ddc1f0aada
        name: my-nodejs
        resources: {}
status: {}
